import type { Metadata } from "next";
import { Inter, Outfit, JetBrains_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      afterSignOutUrl="/sign-in"
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "#22d3ee",
          colorBackground: "#0b0b0c",
          colorText: "#f4f4f5",
          colorInputBackground: "rgba(255, 255, 255, 0.03)",
          colorInputText: "#f4f4f5",
          colorDanger: "#ef4444",
          colorSuccess: "#22d3ee",
          colorWarning: "#fb923c",
          colorTextOnPrimaryBackground: "#000000",
          borderRadius: "0.75rem",
        },
        elements: {
          card: "bg-card/50 backdrop-blur-xl border border-border shadow-2xl shadow-black/50",
          headerTitle: "text-foreground font-semibold",
          headerSubtitle: "text-muted-foreground",
          socialButtonsBlockButton: "border-border bg-card/50 hover:bg-white/[0.04] hover:border-ring transition-all duration-300 text-foreground",
          socialButtonsBlockButtonText: "text-foreground font-medium",
          dividerLine: "bg-border",
          dividerText: "text-muted-foreground",
          formFieldLabel: "text-foreground font-medium",
          formFieldInput: "bg-card/50 border-border focus:border-primary focus:ring-1 focus:ring-primary/50 text-foreground placeholder:text-muted-foreground transition-all duration-300",
          formButtonPrimary: "bg-primary text-primary-foreground hover:bg-primary/90 font-medium transition-all duration-300",
          footerActionLink: "text-primary hover:text-primary/80 transition-colors",
          identityPreviewText: "text-foreground",
          identityPreviewEditButtonIcon: "text-muted-foreground hover:text-foreground transition-colors",
        },
      }}
    >
      <html
        lang="en"
        className={`${inter.variable} ${outfit.variable} ${jetbrainsMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          {children}
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
